### ISSUE TITLE
getFlatNav returning empty result

### ISSUE THREAD

**Issue by teleted** [Vaporbook/BookGluttonEpub#1]
This function returns an empty value. 

   public function getFlatNav()
   {
      // returns all navpoints in document order, flat structure
      return $this->ncx->getElementsByTagName('navPoint');
   }

Using the files dated November 1, 2011 on the included H. G. Wells book.

**Comment by Vaporbook** [comment]
Thanks, ted -- can you include some of the code you're using so I can see the context of the method call? It would be helpful to see any other method calls between instantiation and this call... thanks.

**Comment by teleted** [comment]
This is what I'm using to do a simple test:

```
<?php

require_once('./BookGluttonEpub.php');
require_once('./BookGluttonZipEpub.php');

$file = './H. G. Wells - The War of the Worlds.epub';

echo "Opening $file as OPS in temp dir:\n";

$epub = new BookGluttonEpub();
$epub->open($file);
print_r($epub->getMetaPairs());

echo "Now opening $file as virtual zip (no filesystem on disk):\n";

$epub = new BookGluttonZipEpub();
$epub->loadZip($file);
print_r($epub->getMetaPairs());

print "Next array output: getFlatNav\n";
print_r($epub->getFlatNav());

```

**Comment by Vaporbook** [comment]
Hey ted, thanks for bringing this to my attention. I've added a different way of testing that method which I think will give you the results you wanted. It turns out the method does indeed return a DomNodeList, but print_r will not expose any of the contents of that, so I've added a loop that will display the NCX label values for you. Also, note that there is another function getNavPoints, which is more commonly used, that can return the actual nesting structure of the ncx, rather than as a flat list.  It's more useful if you actually need to render the ncx as a usable table of contents in a reading system. ---A
